version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: monitoring-db
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor123
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor -d monitoring"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: monitoring-backend
    ports:
      - "8002:8002"   # HTTP (HTTPS handled by nginx)
    env_file:
      - ../backend/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../backend:/app
      - ../static:/app/static
    restart: unless-stopped

volumes:
  timescale_data:
